name: Build LaTeX
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: master.tex
      - name: Upload LaTeX Artifact
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: master.pdf
  update_readme:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: output
          path: .
      - name: Run local changes
        run: |
            sudo apt-get install python3-setuptools
            ls
            pwd
            cd .internals/scripts/utils
            pip3 install -r requirements.txt
            ./ubuntu_updateLabels.sh
      - name: Commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Updated Labels" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
